---
- name: Setup ingress controller
  hosts: k8s_master
  vars_files: vars/nginx.yml
  tasks:
    - name: Deploying the ingress controller.
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml

    - name: Configuring the ingress controller.
      k8s:
          definition: "{{ lookup('template', 'files/templates/NGINX-Ingress/svc_nginx_ingress_controller.yml.j2') | from_yaml }}"
