---
- hosts: k8s_master:k8s_nodes
  tasks:
      - name: Waiting for Debian to finish booting.
        pause:
          seconds: 30

      - name: Waiting for Debian to finish performing automatic updates before continuing.
        script: ../files/bash_scripts/monitor_automatic_updates_status.sh

      - name: Performing a Package Upgrade.
        become: yes
        apt:
            name: '*'
            state: latest

      - name: Installing the base packages.
        become: yes
        apt:
            name: ['apt-transport-https', 'bmon', 'ca-certificates', 'curl', 'gnupg2', 'htop', 'iotop', 'openssl', 'python-pip', 'software-properties-common', 'vim']

      - name: Adding Docker's official GPG key.
        become: yes
        apt_key: 
          url: https://download.docker.com/linux/debian/gpg

      - name: Adding Kubernetes' official GPG key.
        become: yes
        apt_key: 
          url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

      - name: Adding the Docker repository.
        become: yes
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable

      - name: Adding the Kubernetes repository.
        become: yes
        apt_repository:
          repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

      - name: Updating the package repositories.
        become: yes
        apt: 
          update_cache: yes

      - name: Installing the required packages to bootstrap a kubernetes cluster.
        become: yes
        apt:
            name: ['docker-ce', 'kubelet', 'kubeadm', 'kubectl']

      - name: Installing the necessary Python library dependencies to use the `k8s` Ansible module.
        become: yes
        pip:
          name: ['openshift', 'kubernetes', 'pyyaml']

      - name: Enabling the systemd module for docker-ce.
        become: yes
        systemd: 
            state: started
            name: docker
            enabled: yes

      - name: Enabling the systemd module for the kubelet.
        become: yes
        systemd:
            state: started
            name: kubelet
            enabled: yes
